#' Download the Mouse Brain Atlas ontology as a list object
#'
#' No parameters
#'
#' @return a nested list object containing the Mouse Brain Atlas ontology
#'
get_mba_ontology <- function() {
  library(jsonlite)

  # Download the ontology JSON file
  temp <- tempfile()
  download.file("http://api.brain-map.org/api/v2/structure_graph_download/1.json", temp)

  # Read the JSON
  raw_ontology <- fromJSON(temp)[["msg"]]

  return(raw_ontology)
}

#' Convert a nested Mouse Brain Atlas ontology to a data.frame
#'
#' @param ontology A nested ontology object
#' @param ongology_df An existing ontology data.frame. This is used for recursion. You should use the default, NULL, to extract a full ontology.
#'
#' @return a data.frame with all descriptive columns for the ontology.
#'
flatten_mba_ontology <- function(ontology, ontology_df = NULL) {
  library(purrr)

  l <- ontology

  if(is.null(ontology_df)) {
    ontology_df <- data.frame(l[names(l) != "children"])[0,]
    ontology_df$n_children <- numeric()
  }

  if("children" %in% names(l)) {

    child_df <- data.frame(l[names(l) != "children"])

    n_children_of_children <- map_dbl(l$children,
                                      function(x) {
                                        if("children" %in% names(x)) {
                                          length(x$children)
                                        } else {
                                          0
                                        }
                                      })

    child_df$n_children <- n_children_of_children

    ontology_df <- rbind(ontology_df, child_df)

    for(i in 1:length(l$children)) {

      child_list <- l$children[[i]]

      ontology_df <- flatten_mba_ontology(child_list, ontology_df)
    }
  }

  return(ontology_df)
}

#' Generate a taxon column that shows the "lineage" of each ontology term
#'
#' @param flat_ontology A flat ontology object generated by flatten_mba_ontology
#'
#' @return a data.frame with all descriptive columns for the ontology plus a new taxon column.
#'
generate_mba_taxons <- function(flat_ontology) {
  flat_ontology <- arrange(flat_ontology,st_level)

  taxons <- list("997" = "0")

  for(i in 2:nrow(flat_ontology)) {
    id <- as.character(flat_ontology$id[i])
    parent_id <- as.character(flat_ontology$parent_structure_id[i])

    taxons[id] <- paste0(taxons[parent_id], ";", id)
  }
  flat_ontology$taxons <- unlist(taxons)
  return(flat_ontology)
}

#' Filter the MBA ontology to find children of a given structure acronym
#'
#' @param flat_ontology A flat ontology data.frame generated by flatten_mba_ontology
#' @param parent_acronym The acronym of a brain ontology structure to find
#' @param include_parent Whether or not to include the parent structure in the output. Default = FALSE.
#'
#' @return A data.frame with the filtered ontology only for children of the parent structure.
filter_mba_ontology_children <- function(flat_ontology,
                                       parent_acronym,
                                       include_parent = FALSE) {

  if(!parent_acronym %in% flat_ontology$acronym) {
    stop(paste0("Parent acronym ", parent_acronym," not found in ontology."))
  }

  if(!"taxons" %in% names(flat_ontology)) {
    flat_ontology <- generate_mba_taxons(flat_ontology)
  }

  parent_taxon <- flat_ontology$taxon[flat_ontology$acronym == parent_acronym]

  children_ontology <- flat_ontology[grepl(paste0("^",parent_taxon), flat_ontology$taxon),]

  if(!include_parent) {
    children_ontology <- children_ontology[children_ontology$taxon != parent_taxon,]
  }

  return(children_ontology)
}

